
var evance={version:'1.0',path:'js/',loaded:new Array(),pageLoaded:false,lang:'en',_debugger:false,_autoId:1,debug:function(object,title){if(this._debugger){evance.core.Debugger.add(object,title);}},inArray:function(value,array){for(var i=0;i<array.length;i++){if(array[i]===value)return true;}
return false;},using:function(api){api=api.split('.');api=evance.path+api.join('/')+'.js';evance.load('script',api);},isLoaded:function(src){return(evance.inArray(src,evance.loaded));},load:function(type,src){var loadDynamically=evance.pageLoaded;if(!evance.isLoaded(src)){if(loadDynamically){var myScript=null;var head=document.getElementsByTagName('head')[0];if(type=='css'){myScript=document.createElement("link");myScript.type="text/css";myScript.href=src;myScript.rel="stylesheet";}else if(type=='script'){myScript=document.createElement('script');myScript.type='text/javascript';myScript.language='javascript';myScript.src=src;}
if(myScript!=null)head.appendChild(myScript);}else{if(type=='css'){document.write('<link href="'+src+'" type="text/css" rel="stylesheet"></link>');}else if(type=='script'){document.write('<script src="'+src+'" language="javascript" type="text/javascript"><\/script>');}}
evance.loaded[evance.loaded.length]=src;}},extend:function(){var args=arguments;if(!args[1])args=[this,args[0]];var subClass=args[0];var baseClass=args[1];function inheritance(){};inheritance.prototype=baseClass.prototype;subClass.prototype=new inheritance();subClass.prototype.constructor=subClass;subClass.prototype.parent=baseClass;subClass.superClass=baseClass.prototype;},getFunctionName:function(f){if(/function (\w+)/.test(String(f))){var _name=RegExp.$1;return _name;}else{return"";}},instanceOf:function(instance){if(instance._className)return instance._className;return $type(instance);},disableSelect:function(el){el=$(el);if($defined(el.onselectstart)){el.onselectstart=function(){return false;};}else if($defined(el.style.MozUserSelect)){el.style.MozUserSelect='none';}
el.unselectable="on";el.style.cursor='default';},enableSelect:function(el){el=$(el);if($defined(el.onselectstart)){el.onselectstart=function(){return true;};}else if($defined(el.style.MozUserSelect)){el.style.MozUserSelect='';}
el.unselectable="off";el.style.cursor='auto';}};evance.event={};evance.event.fix=function(event){if(!event)event=window.event;if(event.target){if(event.target.nodeType==3)event.target=event.target.parentNode;}else if(event.srcElement){event.target=event.srcElement;}
return event;}
evance.event.stopEventPropogation=function(e){if(e.stopPropagation)e.stopPropagation();else e.cancelBubble=true;}
evance.event.stopDefaultAction=function(e){if(e.preventDefault)e.preventDefault();else e.returnValue=false;}
evance.event.EventListener=function(id,type,element,listenerObject,target){this.id=id;this.type=type;this.listener=listenerObject;this.element=element;this.target=target;}
evance.error={};evance.error.handler=function(message,url,line){if(evance._debugger){var myObject={Message:message,URL:url,Line:line};var notes=0;if(!window.gecko){++notes;myObject['Note'+notes]="For a more accurate error message try Firefox with the Firebug extension.";}
if(line==1){++notes;myObject['Note'+notes]="This looks like an event error.";}
evance.debug(myObject,'Error');return false;}else{return true;}}
window.onerror=evance.error.handler;using=evance.using;evance.core={};evance.ui={};