var text_fields_group = {"format":{"eimages":["./images/i_text.gif","./images/i_text.gif","./images/page.gif","./images/minus.gif","./images/minusbottom.gif","./images/plus.gif","./images/plusbottom.gif","./images/line.gif","./images/join.gif","./images/joinbottom.gif"]}};
var text_field = {"format":{"eimages":["./images/i_text.gif","./images/i_text.gif","./images/hline.gif","./images/minus.gif","./images/minusbottom.gif","./images/plus.gif","./images/plusbottom.gif","./images/line.gif","./images/join.gif","./images/joinbottom.gif"]}};
var password_fields_group = {"format":{"eimages":["./images/i_password.gif","./images/i_password.gif","./images/page.gif","./images/minus.gif","./images/minusbottom.gif","./images/plus.gif","./images/plusbottom.gif","./images/line.gif","./images/join.gif","./images/joinbottom.gif"]}};
var password_field = {"format":{"eimages":["./images/i_text.gif","./images/i_text.gif","./images/hline.gif","./images/minus.gif","./images/minusbottom.gif","./images/plus.gif","./images/plusbottom.gif","./images/line.gif","./images/join.gif","./images/joinbottom.gif"]}};
var combo_boxes_group = {"format":{"eimages":["./images/i_combo.gif","./images/i_combo.gif","./images/page.gif","./images/minus.gif","./images/minusbottom.gif","./images/plus.gif","./images/plusbottom.gif","./images/line.gif","./images/join.gif","./images/joinbottom.gif"]}};
var combo_box = {"format":{"eimages":["./images/i_text.gif","./images/i_text.gif","./images/hline.gif","./images/minus.gif","./images/minusbottom.gif","./images/plus.gif","./images/plusbottom.gif","./images/line.gif","./images/join.gif","./images/joinbottom.gif"]}};

var type_doc1 = {"format":{"eimages":["./images/i_document.gif","./images/i_document.gif","./images/i_document.gif","./images/minus.gif","./images/minusbottom.gif","./images/plus.gif","./images/plusbottom.gif","./images/line.gif","./images/join.gif","./images/joinbottom.gif"]}};
var type_doc2 = {"format":{"eimages":["./images/i_sound.gif","./images/i_sound.gif","./images/i_sound.gif","./images/minus.gif","./images/minusbottom.gif","./images/plus.gif","./images/plusbottom.gif","./images/line.gif","./images/join.gif","./images/joinbottom.gif"]}};
var type_doc3 = {"format":{"eimages":["./images/i_picture.gif","./images/i_picture.gif","./images/i_picture.gif","./images/minus.gif","./images/minusbottom.gif","./images/plus.gif","./images/plusbottom.gif","./images/line.gif","./images/join.gif","./images/joinbottom.gif"]}};
