<Id>[SAGE_CUSTOMER_ID]</Id>
<CompanyName>[SAGE_CUSTOMER_COMPANYNAME]</CompanyName>
<AccountReference>[SAGE_CUSTOMER_ACCOUNTREFERENCE]</AccountReference>
<VatNumber></VatNumber>
<CreditLimit>[SAGE_CUSTOMER_CREDITLIMIT]</CreditLimit>
<Balance></Balance>
<CustomerInvoiceAddress>[SAGE_CUSTOMER_INVOICEADDRESS]</CustomerInvoiceAddress>
<CustomerDeliveryAddress>[SAGE_CUSTOMER_DELIVERYADDRESS]</CustomerDeliveryAddress>
<Currency>[SAGE_CUSTOMER_CURRENCY]</Currency>
<TermsAgreed>[SAGE_CUSTOMER_TERMS]</TermsAgreed>
<PriceListReference></PriceListReference>
<AccountStatus></AccountStatus>
<Analysis1></Analysis1>
<Analysis2></Analysis2>
<Analysis3></Analysis3>
<ShortName></ShortName>
<Contacts>[SAGE_CUSTOMER_CONTACTS]</Contacts>
<Memo></Memo>
<BankSortCode></BankSortCode>
<BankAccountNo></BankAccountNo>
<BankAccountName></BankAccountName>
<DiscountType></DiscountType>
<DiscountTable></DiscountTable>
<FixedDiscount></FixedDiscount>
<AccountOnHold></AccountOnHold>
<NominalCode>[SAGE_CUSTOMER_NOMINAL_CODE]</NominalCode>
<CustomFields></CustomFields>