<Title>[SAGE_CONTACT_TITLE]</Title>
<Forename>[SAGE_CONTACT_FORENAME]</Forename>
<Surname>[SAGE_CONTACT_SURNAME]</Surname>
<Company>[SAGE_CONTACT_COMPANY]</Company>
<Address1>[SAGE_CONTACT_ADDRESS1]</Address1>
<Address2>[SAGE_CONTACT_ADDRESS2]</Address2>
<Address3>[SAGE_CONTACT_ADDRESS3]</Address3>
<Town>[SAGE_CONTACT_TOWN]</Town>
<Postcode>[SAGE_CONTACT_POSTCODE]</Postcode>
<County>[SAGE_CONTACT_COUNTY]</County>
<Country>[SAGE_CONTACT_COUNTRY]</Country>
<Telephone>[SAGE_CONTACT_TELEPHONE]</Telephone>
<Fax>[SAGE_CONTACT_FAX]</Fax>
<Mobile>[SAGE_CONTACT_MOBILE]</Mobile>
<Email>[SAGE_CONTACT_EMAIL]</Email>
<Website></Website>
<Status></Status>
<Spouse></Spouse>
<Birthdate></Birthdate>
<ReferredBy></ReferredBy>
<LastResults></LastResults>
<Notes>[SAGE_CONTACT_NOTES]</Notes>
<TaxCode></TaxCode>
<CustomFields></CustomFields>