<Id>[SAGE_INVOICE_ID]</Id>
<CustomerId>[SAGE_INVOICE_CUSTOMERID]</CustomerId>
<InvoiceNumber>[SAGE_INVOICE_INVOICENUMBER]</InvoiceNumber>
<CustomerOrderNumber>[SAGE_INVOICE_CUSTOMERORDERNUMBER]</CustomerOrderNumber>
<AccountReference>[SAGE_INVOICE_ACCOUNTREFERENCE]</AccountReference>
<OrderNumber>[SAGE_INVOICE_ORDERNUMBER]</OrderNumber>
<ForeignRate></ForeignRate>
<Currency>[SAGE_INVOICE_CURRENCY]</Currency>
<Notes1>[SAGE_INVOICE_NOTES_1]</Notes1>
<Notes2>[SAGE_INVOICE_NOTES_2]</Notes2>
<Notes3>[SAGE_INVOICE_NOTES_3]</Notes3>
<CurrencyUsed></CurrencyUsed>
<InvoiceDate>[SAGE_INVOICE_DATE]</InvoiceDate>
<InvoiceAddress>[SAGE_INVOICE_INVOICEADDRESS]</InvoiceAddress>
<InvoiceDeliveryAddress>[SAGE_INVOICE_DELIVERYADDRESS]</InvoiceDeliveryAddress>
<InvoiceItems>[SAGE_INVOICE_ITEMS]</InvoiceItems>
<Carriage>[SAGE_INVOICE_CARRIAGE]</Carriage>
<InvoiceType>[SAGE_INVOICE_TYPE]</InvoiceType>
<TakenBy></TakenBy>
<ConsignmentNo></ConsignmentNo>
<Courier></Courier>
<SettlementDays></SettlementDays>
<SettlementDiscount></SettlementDiscount>
<GlobalNominalCode>[SAGE_INVOICE_NOMINALCODE]</GlobalNominalCode>
<GlobalDetails>[SAGE_INVOICE_DETAILS]</GlobalDetails>
<GlobalTaxCode>[SAGE_INVOICE_TAXCODE]</GlobalTaxCode>
<GlobalDepartment>[SAGE_INVOICE_DEPARTMENT]</GlobalDepartment>
<PaymentRef>[SAGE_INVOICE_PAYMENTREFERENCE]</PaymentRef>
<PaymentAmount>[SAGE_INVOICE_PAYMENTAMOUNT]</PaymentAmount>
<BankAccount>[SAGE_INVOICE_BANKACCOUNT]</BankAccount>
<PaymentType>[SAGE_INVOICE_PAYMENTTYPE]</PaymentType>
<PostedDate>[SAGE_INVOICE_POSTEDDATE]</PostedDate>
<PaidFlag></PaidFlag>
<AmountPaid></AmountPaid>