<Id>[SAGE_PRODUCT_ID]</Id>
<Sku>[SAGE_PRODUCT_SKU]</Sku>
<Barcode></Barcode>
<Name>[SAGE_PRODUCT_NAME]</Name>
<Description>[SAGE_PRODUCT_DESCRIPTION]</Description>
<LongDescription>[SAGE_PRODUCT_LONGDESCRIPTION]</LongDescription>
<ImageUrl></ImageUrl>
<ThumbnailUrl></ThumbnailUrl>
<Custom1></Custom1>
<Custom2></Custom2>
<Custom3></Custom3>
<SalePrice>[SAGE_PRODUCT_PRICE]</SalePrice>
<UnitWeight>[SAGE_PRODUCT_WEIGHT]</UnitWeight>
<QtyInStock>[SAGE_PRODUCT_QUANTITYINSTOCK]</QtyInStock>
<QtyOnOrder>[SAGE_PRODUCT_QUANTITYONORDER]</QtyOnOrder>
<ReorderQty>[SAGE_PRODUCT_REORDERQUANTITY]</ReorderQty>
<TaxCode>[SAGE_PRODUCT_TAXCODE]</TaxCode>
<GroupCode></GroupCode>
<Department>[SAGE_PRODUCT_DEPARTMENT]</Department>
<UnitOfSale></UnitOfSale>
<NominalCode></NominalCode>
<CostCentre></CostCentre>
<Publish>[SAGE_PRODUCT_PUBLISH]</Publish>
<SpecialOffer>[SAGE_PRODUCT_SPECIALOFFER]</SpecialOffer>
<QtyAllocated></QtyAllocated>
<Image></Image>
<ImageName></ImageName>
<Attachments></Attachments>
<DateModified></DateModified>
<Dimensions></Dimensions>
<ProductBoms></ProductBoms>
<RelatedProducts></RelatedProducts>
<AlternativeProducts></AlternativeProducts>
<SupplierNominalCode></SupplierNominalCode>
<SupplierCostCentre></SupplierCostCentre>
<SupplierDepartment></SupplierDepartment>
<ProductQtyBreaks></ProductQtyBreaks>
<CommodityCode></CommodityCode>
<Memo></Memo>
<Manufacturer>[SAGE_PRODUCT_MANUFACTURER]</Manufacturer>
<ManufacturerPartNo></ManufacturerPartNo>
<Attributes></Attributes>
<ItemType>[SAGE_PRODUCT_ITEMTYPE]</ItemType>