<Id>[SAGE_ITEM_ID]</Id>
<Sku>[SAGE_ITEM_SKU]</Sku>
<Name>[SAGE_ITEM_NAME]</Name>
<Description>[SAGE_ITEM_DESCRIPTION]</Description>
<Comments>[SAGE_ITEM_COMMENTS]</Comments>
<UnitOfSale></UnitOfSale>
<QtyOrdered>[SAGE_ITEM_QUANTITY]</QtyOrdered>
<UnitPrice>[SAGE_ITEM_PRICE]</UnitPrice>
<UnitDiscountAmount>[SAGE_ITEM_DISCOUNTAMOUNT]</UnitDiscountAmount>
<UnitDiscountPercentage>[SAGE_ITEM_DISCOUNTPERCENTAGE]</UnitDiscountPercentage>
<Reference>[SAGE_ITEM_REFERENCE]</Reference>
<TaxRate>[SAGE_ITEM_TAXRATE]</TaxRate>
<TotalNet>[SAGE_ITEM_TOTALNET]</TotalNet>
<TotalTax>[SAGE_ITEM_TOTALTAX]</TotalTax>
<TaxCode>[SAGE_ITEM_TAXCODE]</TaxCode>
<NominalCode>[SAGE_ITEM_NOMINALCODE]</NominalCode>
<CostCentre></CostCentre>
<Department>[SAGE_ITEM_DEPARTMENT]</Department>
<Text></Text>
<Type>[SAGE_ITEM_TYPE]</Type>
<QtyAllocated></QtyAllocated>
<QtyDespatched></QtyDespatched>
<Status></Status>