<?php

$GLOBALS['SYSTEM_LANGUAGE'] = 1;
$GLOBALS['SYSTEM_CURRENCY'] = 3;
$GLOBALS['SYSTEM_COUNTRY'] = 222;
$GLOBALS['SYSTEM_REGION'] = 2144;
$GLOBALS['SYSTEM_ADDRESS_FORMAT_SHORT'] = '[city][sep][country]';
$GLOBALS['SYSTEM_ADDRESS_FORMAT_LONG'] = '[streets][sep][city][sep][region]   [zip][sep][country]';
$GLOBALS['DATE_FORMAT_SHORT'] = 'd/m/Y';
$GLOBALS['DATE_FORMAT_LONG'] = 'D jS F Y';
$GLOBALS['DATE_TIME_FORMAT'] = 'd/m/Y H:i:s';
$GLOBALS['DB_DATE_TIME_FORMAT'] = 'Y-m-d H:i:s';
$GLOBALS['DATE_TIME_FORMAT_LONG'] = 'D jS M Y H:i:s';

$GLOBALS['CACHE_DIR_WS'] = "/cache/";
$GLOBALS['CACHE_DIR_FS'] = $GLOBALS['DIR_WS_ROOT'] . "cache/";

$GLOBALS['PRODUCT_IMG_MIN_WIDTH'] = NULL;
$GLOBALS['PRODUCT_IMG_MIN_HEIGHT'] = NULL;
$GLOBALS['PRODUCT_THUMB_MIN_WIDTH'] = NULL;
$GLOBALS['PRODUCT_THUMB_MIN_HEIGHT'] = NULL;
$GLOBALS['PRODUCT_IMG_MAX_WIDTH'] = 400;
$GLOBALS['PRODUCT_IMG_MAX_HEIGHT'] = 400;
$GLOBALS['PRODUCT_THUMB_MAX_WIDTH'] = 100;
$GLOBALS['PRODUCT_THUMB_MAX_HEIGHT'] = 100;
$GLOBALS['PRODUCT_IMAGES_DIR_WS'] = "/images/products/";
$GLOBALS['PRODUCT_IMAGES_DIR_FS'] = $GLOBALS['DIR_WS_ROOT'] . "images/products/";

$GLOBALS['PRODUCT_LINK_IMAGE_MIN_WIDTH'] = NULL;
$GLOBALS['PRODUCT_LINK_IMAGE_MIN_HEIGHT'] = NULL;
$GLOBALS['PRODUCT_LINK_IMAGE_MAX_WIDTH'] = 75;
$GLOBALS['PRODUCT_LINK_IMAGE_MAX_HEIGHT'] = 75;

$GLOBALS['PRODUCT_EXAMPLE_IMAGE_MIN_WIDTH'] = NULL;
$GLOBALS['PRODUCT_EXAMPLE_IMAGE_MIN_HEIGHT'] = NULL;
$GLOBALS['PRODUCT_EXAMPLE_THUMB_MIN_WIDTH'] = NULL;
$GLOBALS['PRODUCT_EXAMPLE_THUMB_MIN_HEIGHT'] = NULL;
$GLOBALS['PRODUCT_EXAMPLE_IMAGE_MAX_WIDTH'] = NULL;
$GLOBALS['PRODUCT_EXAMPLE_IMAGE_MAX_HEIGHT'] = NULL;
$GLOBALS['PRODUCT_EXAMPLE_THUMB_MAX_WIDTH'] = 100;
$GLOBALS['PRODUCT_EXAMPLE_THUMB_MAX_HEIGHT'] = 100;
$GLOBALS['PRODUCT_EXAMPLE_IMAGES_DIR_WS'] = "/images/examples/";
$GLOBALS['PRODUCT_EXAMPLE_IMAGES_DIR_FS'] = $GLOBALS['DIR_WS_ROOT'] . "images/examples/";

$GLOBALS['SPEC_IMAGE_MIN_WIDTH'] = NULL;
$GLOBALS['SPEC_IMAGE_MIN_HEIGHT'] = NULL;
$GLOBALS['SPEC_IMAGE_MAX_WIDTH'] = 200;
$GLOBALS['SPEC_IMAGE_MAX_HEIGHT'] = 200;
$GLOBALS['SPEC_IMAGES_DIR_WS'] = "/images/specs/";
$GLOBALS['SPEC_IMAGES_DIR_FS'] = $GLOBALS['DIR_WS_ROOT'] . "images/specs/";

$GLOBALS['SERVER_IMG_PROCESSOR'] = "GD";
$GLOBALS['SYSTEM_CLOCK'] = "GMT";
$GLOBALS['SERVER_CLOCK'] = "GMT";

$GLOBALS['BASE_IMG_MIN_WIDTH'] = NULL;
$GLOBALS['BASE_IMG_MIN_HEIGHT'] = NULL;
$GLOBALS['BASE_IMG_MAX_WIDTH'] = 100;
$GLOBALS['BASE_IMG_MAX_HEIGHT'] = 100;
$GLOBALS['BASE_IMAGES_DIR_WS'] = "/images/bases/";
$GLOBALS['BASE_IMAGES_DIR_FS'] = $GLOBALS['DIR_WS_ROOT'] . "images/bases/";

$GLOBALS['TRADE_IMG_MIN_WIDTH'] = NULL;
$GLOBALS['TRADE_IMG_MIN_HEIGHT'] = NULL;
$GLOBALS['TRADE_IMG_MAX_WIDTH'] = 300;
$GLOBALS['TRADE_IMG_MAX_HEIGHT'] = 120;
$GLOBALS['TRADE_IMAGES_DIR_WS'] = "/images/trade/";
$GLOBALS['TRADE_IMAGES_DIR_FS'] = $GLOBALS['DIR_WS_ROOT'] . "images/trade/";

// Category Images
$GLOBALS['CATEGORY_IMG_MIN_WIDTH'] = NULL;
$GLOBALS['CATEGORY_IMG_MIN_HEIGHT'] = NULL;
$GLOBALS['CATEGORY_THUMB_MIN_WIDTH'] = NULL;
$GLOBALS['CATEGORY_THUMB_MIN_HEIGHT'] = NULL;
$GLOBALS['CATEGORY_IMG_MAX_WIDTH'] = 500;
$GLOBALS['CATEGORY_IMG_MAX_HEIGHT'] = 400;
$GLOBALS['CATEGORY_THUMB_MAX_WIDTH'] = 200;
$GLOBALS['CATEGORY_THUMB_MAX_HEIGHT'] = 200;
$GLOBALS['CATEGORY_IMAGES_DIR_WS'] = "/images/categories/";
$GLOBALS['CATEGORY_IMAGES_DIR_FS'] = $GLOBALS['DIR_WS_ROOT'] . "images/categories/";

$GLOBALS['CATEGORY_CATALOGUE_THUMB_MIN_WIDTH'] = NULL;
$GLOBALS['CATEGORY_CATALOGUE_THUMB_MIN_HEIGHT'] = NULL;
$GLOBALS['CATEGORY_CATALOGUE_THUMB_MAX_WIDTH'] = 200;
$GLOBALS['CATEGORY_CATALOGUE_THUMB_MAX_HEIGHT'] = 200;
$GLOBALS['CATEGORY_CATALOGUE_THUMB_DIR_WS'] = "/images/catalogue/";
$GLOBALS['CATEGORY_CATALOGUE_THUMB_DIR_FS'] = $GLOBALS['DIR_WS_ROOT'] . "images/catalogue/";
$GLOBALS['CATEGORY_CATALOGUE_IMAGE_DIR_WS'] = "/images/catalogue/";
$GLOBALS['CATEGORY_CATALOGUE_IMAGE_DIR_FS'] = $GLOBALS['DIR_WS_ROOT'] . "images/catalogue/";

// Link Images
$GLOBALS['LINKS_IMG_MIN_WIDTH'] = NULL;
$GLOBALS['LINKS_IMG_MIN_HEIGHT'] = NULL;
$GLOBALS['LINKS_IMG_MAX_WIDTH'] = 150;
$GLOBALS['LINKS_IMG_MAX_HEIGHT'] = 100;
$GLOBALS['LINKS_IMAGES_DIR_WS'] = "/images/links/";
$GLOBALS['LINKS_IMAGES_DIR_FS'] = $GLOBALS['DIR_WS_ROOT'] . "images/links/";

// Affiliate Images
$GLOBALS['AFFILIATES_IMG_MIN_WIDTH'] = NULL;
$GLOBALS['AFFILIATES_IMG_MIN_HEIGHT'] = NULL;
$GLOBALS['AFFILIATES_IMG_MAX_WIDTH'] = 150;
$GLOBALS['AFFILIATES_IMG_MAX_HEIGHT'] = 100;
$GLOBALS['AFFILIATES_IMAGES_DIR_WS'] = "/images/affiliates/";
$GLOBALS['AFFILIATES_IMAGES_DIR_FS'] = $GLOBALS['DIR_WS_ROOT'] . "images/affiliates/";

$GLOBALS['BROCHURE_MENU_IMAGE_MIN_WIDTH'] = NULL;
$GLOBALS['BROCHURE_MENU_IMAGE_MIN_HEIGHT'] = NULL;
$GLOBALS['BROCHURE_MENU_IMAGE_MAX_WIDTH'] = 150;
$GLOBALS['BROCHURE_MENU_IMAGE_MAX_HEIGHT'] = 160;
$GLOBALS['BROCHURE_MENU_IMAGE_DIR_WS'] = "/images/brochures/";
$GLOBALS['BROCHURE_MENU_IMAGE_DIR_FS'] = $GLOBALS['DIR_WS_ROOT'] . "images/brochures/";
$GLOBALS['BROCHURE_SPREAD_IMAGE_MIN_WIDTH'] = NULL;
$GLOBALS['BROCHURE_SPREAD_IMAGE_MIN_HEIGHT'] = NULL;
$GLOBALS['BROCHURE_SPREAD_IMAGE_MAX_WIDTH'] = 200;
$GLOBALS['BROCHURE_SPREAD_IMAGE_MAX_HEIGHT'] = 200;
$GLOBALS['BROCHURE_SPREAD_IMAGE_DIR_WS'] = "/images/brochures/";
$GLOBALS['BROCHURE_SPREAD_IMAGE_DIR_FS'] = $GLOBALS['DIR_WS_ROOT'] . "images/brochures/";

$GLOBALS['LOGO_IMAGE_MIN_WIDTH'] = NULL;
$GLOBALS['LOGO_IMAGE_MIN_HEIGHT'] = NULL;
$GLOBALS['LOGO_IMAGE_MAX_WIDTH'] = 500;
$GLOBALS['LOGO_IMAGE_MAX_HEIGHT'] = 70;
$GLOBALS['LOGO_IMAGE_DIR_WS'] = "/images/logos/";
$GLOBALS['LOGO_IMAGE_DIR_FS'] = $GLOBALS['DIR_WS_ROOT'] . "images/logos/";

$GLOBALS['EMAIL_BANNER_IMAGE_MIN_WIDTH'] = 650;
$GLOBALS['EMAIL_BANNER_IMAGE_MIN_HEIGHT'] = NULL;
$GLOBALS['EMAIL_BANNER_IMAGE_MAX_WIDTH'] = 650;
$GLOBALS['EMAIL_BANNER_IMAGE_MAX_HEIGHT'] = 2600;
$GLOBALS['EMAIL_BANNER_IMAGES_DIR_WS'] = "/images/email/banner/";
$GLOBALS['EMAIL_BANNER_IMAGES_DIR_FS'] = $GLOBALS['DIR_WS_ROOT'] . "images/email/banner/";
$GLOBALS['EMAIL_PANEL_IMAGES_DIR_WS'] = "/images/email/panel/";
$GLOBALS['EMAIL_PANEL_IMAGES_DIR_FS'] = $GLOBALS['DIR_WS_ROOT'] . "images/email/panel/";

// Shipping Config
$GLOBALS['DEFAULT_SHIPPING_COUNTRY'] = 222;
$GLOBALS['DEFAULT_SHIPPING_REGION'] = 2144;
$GLOBALS['DEFAULT_TAX_ON_SHIPPING'] = 3;
$GLOBALS['DEFAULT_POSTAGE'] = 1;

// Email Defaults
$GLOBALS['EMAIL_TECHNICAL'] = 'support@azexis.com';
$GLOBALS['EMAIL_FROM'] = "no-reply@bltdirect.com";
$GLOBALS['EMAIL_SUPPORT'] = "customerservices@bltdirect.com";
$GLOBALS['EMAIL_SALES'] = "sales@bltdirect.com";
$GLOBALS['EMAIL_RETURN'] = "failure@mailer.bltdirect.com";
$GLOBALS['EMAIL_DAEMON'] = "mailer-daemon@server217-174-252-254.live-servers.net";
$GLOBALS['EMAIL_ERRORS_FROM'] = "error-reporter@bltdirect.com";
$GLOBALS['EMAIL_DEVELOPER_LOG'] = "bug@azexis.com";

$GLOBALS['SMTP_HOST'] = '217.174.250.56';

$GLOBALS['COMPANY'] = "BLT Direct";
$GLOBALS['COMPANY_PHONE'] = "+44 (0)1473 716 418";
$GLOBALS['COMPANY_DESCRIPTION'] = "BLT Direct has been a leading online supplier of light bulbs, lamps and tubes in the UK and around the world since the early days of the Internet. Our website provides instant access to almost 10,000 products including Energy Saving Light Bulbs, Halogen Light Bulbs, Fluorescent Tubes, Incandescent Light Bulbs, Metal Halide Lamps, LED Light Bulbs, Compact Fluorescent, Sodium Lamps, Mercury Lamps, Sunbed Tubes, Specialist Lamps, Light Fittings and Ballasts.";

// Use Search Engine Friendly URLs for category and product pages?
$GLOBALS['USE_SEF_URLS'] = false;

$GLOBALS['DISCOUNT_FROM_RRP'] = false;

$GLOBALS['ARTICLE_DOWNLOAD_DIR_WS'] = "/downloads/articles/";
$GLOBALS['ARTICLE_DOWNLOAD_DIR_FS'] = $GLOBALS['DIR_WS_ROOT'] . "downloads/articles/";
$GLOBALS['BROCHURE_DOWNLOAD_DIR_WS'] = "/downloads/brochures/";
$GLOBALS['BROCHURE_DOWNLOAD_DIR_FS'] = $GLOBALS['DIR_WS_ROOT'] . "downloads/brochures/";
$GLOBALS['PRODUCT_DOWNLOAD_DIR_WS'] = "/downloads/products/";
$GLOBALS['PRODUCT_DOWNLOAD_DIR_FS'] = $GLOBALS['DIR_WS_ROOT'] . "downloads/products/";

// Documents
$GLOBALS['CAMPAIGN_DOCUMENT_DIR_WS'] = "/documents/campaigns/";
$GLOBALS['CAMPAIGN_DOCUMENT_DIR_FS'] = $GLOBALS['DIR_WS_ROOT'] . "documents/campaigns/";
$GLOBALS['ENQUIRY_DOCUMENT_DIR_WS'] = "/documents/enquiries/";
$GLOBALS['ENQUIRY_DOCUMENT_DIR_FS'] = $GLOBALS['DIR_WS_ROOT'] . "documents/enquiries/";
$GLOBALS['AFFILIATE_DOCUMENT_DIR_WS'] = "/documents/affiliates/";
$GLOBALS['AFFILIATE_DOCUMENT_DIR_FS'] = $GLOBALS['DIR_WS_ROOT'] . "documents/affiliates/";
$GLOBALS['RETURN_DOCUMENT_DIR_WS'] = "/documents/returns/";
$GLOBALS['RETURN_DOCUMENT_DIR_FS'] = $GLOBALS['DIR_WS_ROOT'] . "documents/returns/";
$GLOBALS['USER_DOCUMENT_DIR_WS'] = "/documents/users/";
$GLOBALS['USER_DOCUMENT_DIR_FS'] = $GLOBALS['DIR_WS_ROOT'] . "documents/users/";
$GLOBALS['CONTACT_DOCUMENT_DIR_WS'] = "/documents/contacts/";
$GLOBALS['CONTACT_DOCUMENT_DIR_FS'] = $GLOBALS['DIR_WS_ROOT'] . "documents/contacts/";
$GLOBALS['ORDER_DOCUMENT_DIR_WS'] = "/documents/orders/";
$GLOBALS['ORDER_DOCUMENT_DIR_FS'] = $GLOBALS['DIR_WS_ROOT'] . "documents/orders/";
$GLOBALS['ORDER_QUOTE_DOCUMENT_DIR_WS'] = "/documents/orders/quotes/";
$GLOBALS['ORDER_QUOTE_DOCUMENT_DIR_FS'] = $GLOBALS['DIR_WS_ROOT'] . "documents/orders/quotes/";
$GLOBALS['WORKTASK_DOCUMENT_DIR_WS'] = "/documents/worktasks/";
$GLOBALS['WORKTASK_DOCUMENT_DIR_FS'] = $GLOBALS['DIR_WS_ROOT'] . "documents/worktasks/";
$GLOBALS['WORKTASK_ARCHIVE_DOCUMENT_DIR_WS'] = "/documents/worktasks/archives/";
$GLOBALS['WORKTASK_ARCHIVE_DOCUMENT_DIR_FS'] = $GLOBALS['DIR_WS_ROOT'] . "documents/worktasks/archives/";
$GLOBALS['WORKTASK_SCHEDULE_DOCUMENT_DIR_WS'] = "/documents/worktasks/schedules/";
$GLOBALS['WORKTASK_SCHEDULE_DOCUMENT_DIR_FS'] = $GLOBALS['DIR_WS_ROOT'] . "documents/worktasks/schedules/";

$GLOBALS['TEMP_DIR_WS'] = "/ignition/temp/";
$GLOBALS['TEMP_DIR_FS'] = $GLOBALS['DIR_WS_ADMIN'] . "temp/";
$GLOBALS['TEMP_CHART_DIR_WS'] = "/ignition/temp/charts/";
$GLOBALS['TEMP_CHART_DIR_FS'] = $GLOBALS['DIR_WS_ADMIN'] . "temp/charts/";
$GLOBALS['TEMP_REPORT_DIR_WS'] = "/ignition/temp/reports/";
$GLOBALS['TEMP_REPORT_DIR_FS'] = $GLOBALS['DIR_WS_ADMIN'] . "temp/reports/";
$GLOBALS['TEMP_ENQUIRY_DOCUMENT_DIR_WS'] = "/ignition/temp/documents/enquiries/";
$GLOBALS['TEMP_ENQUIRY_DOCUMENT_DIR_FS'] = $GLOBALS['DIR_WS_ADMIN'] . "temp/documents/enquiries/";
$GLOBALS['TEMP_COUPON_DOCUMENT_DIR_WS'] = "/ignition/temp/documents/coupons/";
$GLOBALS['TEMP_COUPON_DOCUMENT_DIR_FS'] = $GLOBALS['DIR_WS_ADMIN'] . "temp/documents/coupons/";
$GLOBALS['TEMP_INVOICE_DOCUMENT_DIR_WS'] = "/ignition/temp/documents/invoices/";
$GLOBALS['TEMP_INVOICE_DOCUMENT_DIR_FS'] = $GLOBALS['DIR_WS_ADMIN'] . "temp/documents/invoices/";

$GLOBALS['SESSION_USER_ID'] = 0;

$GLOBALS['POSTCODEANYWHERE_ACTIVE'] = true;
$GLOBALS['POSTCODEANYWHERE_ACCOUNT'] = 'ELLWO11112';
$GLOBALS['POSTCODEANYWHERE_LICENCE'] = 'NC69-PU58-DG87-YF79';

$GLOBALS['GL_WAREHOUSE'] = 10;
$GLOBALS['JL_WAREHOUSE'] = 11;

$GLOBALS['DATA_DIR_WS'] = "/data/";
$GLOBALS['DATA_DIR_FS'] = $GLOBALS['DIR_WS_ROOT'] . "data/";

$GLOBALS['GOOGLE_CHECKOUT_LIVE'] = true;
$GLOBALS['GOOGLE_CHECKOUT_DEFAULT_TAX'] = (time() < strtotime('2010-01-01 00:00:00')) ? 0.150 : ((time() < strtotime('2011-01-04 00:00:00')) ? 0.175 : 0.2);
$GLOBALS['GOOGLE_CHECKOUT_LIVE_MERCHANT_ID'] = '438238388100479';
$GLOBALS['GOOGLE_CHECKOUT_LIVE_MERCHANT_KEY'] = 'nDKXXjucMNHlZwI3WLYl4Q';
$GLOBALS['GOOGLE_CHECKOUT_SANDBOX_MERCHANT_ID'] = '564984206932766';
$GLOBALS['GOOGLE_CHECKOUT_SANDBOX_MERCHANT_KEY'] = 'mPxOppTLXOqD0Ty_snN7BA';
$GLOBALS['GOOGLE_BASE_API_KEY'] = 'ABQIAAAAXK9KB0-gie7hvDflMrlUqhRgCV_jwT7QUTAgXglXEjJxkcoRNhQHuVEcc69sllXvvm--I53L8D1iXA';
$GLOBALS['GOOGLE_BASE_WS'] = $GLOBALS['DATA_DIR_WS'] . "remote/google/base/";
$GLOBALS['GOOGLE_BASE_FS'] = $GLOBALS['DATA_DIR_FS'] . "remote/google/base/";
$GLOBALS['GOOGLE_SITEMAP_WS'] = "/";
$GLOBALS['GOOGLE_SITEMAP_FS'] = $GLOBALS['DIR_WS_ROOT'];
$GLOBALS['GOOGLE_SITEMAP_MAX'] = 9;

$GLOBALS['PAYPAL_USERNAME'] = 'steve_api1.bltdirect.com';
$GLOBALS['PAYPAL_PASSWORD'] = 'ME4XZ35UZQK3THAT';
$GLOBALS['PAYPAL_SIGNATURE'] = 'ANDVr2qGxFKzfn5YAw7OH8A2qScnAWEnYqKcr0LTe15w-B2CevBAp9wK';

$GLOBALS['PRODUCT_PREFIX'] = '';

// Libraries
$GLOBALS['MEDIA_DIR_WS'] = "/library/media/";
$GLOBALS['MEDIA_DIR_FS'] = $GLOBALS['DIR_WS_ROOT'] . "library/media/";
$GLOBALS['MEDIA_THUMB_MIN_WIDTH'] = NULL;
$GLOBALS['MEDIA_THUMB_MIN_HEIGHT'] = NULL;
$GLOBALS['MEDIA_THUMB_MAX_WIDTH'] = 200;
$GLOBALS['MEDIA_THUMB_MAX_HEIGHT'] = 200;

$GLOBALS['FILE_DIR_WS'] = "/library/file/";
$GLOBALS['FILE_DIR_FS'] = $GLOBALS['DIR_WS_ROOT'] . "library/file/";

$GLOBALS['URLALIAS_DIVIDER'] = '-';

$GLOBALS['SMS_DESTINATION_NUMBER'] = '07850 745101';
$GLOBALS['SMS_ALERT_EMAIL'] = 'steve@bltdirect.com';

$GLOBALS['FASTSMS_USERNAME'] = 'nsp04604';
$GLOBALS['FASTSMS_PASSWORD'] = 'wood64';

$GLOBALS['PRODUCT_REVIEW_RATINGS'] = 5;

$GLOBALS['SAGE_DEPARTMENT_INDEX'] = 2;
$GLOBALS['SAGE_DEPARTMENT_INDEX_LBUK'] = 2;
$GLOBALS['SAGE_DEPARTMENT_KEY'] = 'B';
$GLOBALS['SAGE_BANKACCOUNT'] = 1200;
$GLOBALS['SAGE_INTEGRATION_DATE'] = '2010-05-01 00:00:00';
$GLOBALS['SAGE_INTEGRATION_DATE_LBUK'] = '2010-08-26 00:00:00';
$GLOBALS['SAGE_INTEGRATION_DATE_BATCH'] = '2010-05-01 00:00:00';
$GLOBALS['SAGE_INTEGRATION_DATE_BATCH_LBUK'] = '2010-08-26 00:00:00';
$GLOBALS['SAGE_TAX_EXEMPT_CODE'] = 0;
$GLOBALS['SAGE_DEFAULT_NOMINAL_CODE'] = '4100';
$GLOBALS['SAGE_DEFAULT_NOMINAL_CODE_CREDIT'] = '4106';
$GLOBALS['SAGE_DEFAULT_NOMINAL_CODE_CARRIAGE'] = '4905';
$GLOBALS['SAGE_DEFAULT_NOMINAL_CODE_LBUK'] = '4107';
$GLOBALS['SAGE_DEFAULT_NOMINAL_CODE_CARRIAGE_LBUK'] = '4107';

$GLOBALS['HOME_PAGE_ID'] = 1;
$GLOBALS['DEFAULT_PURGE_CART_RATE'] = 14;